//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorSwitch.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorSwitch.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PolygonStorage xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;SectorStorage&gt;
        ///	&lt;ArrayOfVector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;128&lt;/X&gt;&lt;Y&gt;0&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;191&lt;/X&gt;&lt;Y&gt;17&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;239&lt;/X&gt;&lt;Y&gt;64&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;256&lt;/X&gt;&lt;Y&gt;128&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;234&lt;/X&gt;&lt;Y&gt;128&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;219&lt;/X&gt;&lt;Y&gt;74&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;180&lt;/X&gt;&lt;Y&gt;35&lt;/Y&gt;&lt;/Vector2&gt;
        ///		&lt;Vector2&gt;&lt;X&gt;128&lt;/X&gt;&lt;Y&gt;21&lt;/Y&gt;&lt;/Vector2&gt;
        ///	&lt;/ArrayOfVector2&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PolygonStorage {
            get {
                return ResourceManager.GetString("PolygonStorage", resourceCulture);
            }
        }
    }
}
